Repository Miguelsiqueiros/El-Tempranon-Backend, pull requests merged in 2020-02, with the labels that each got.

#24 Query daily-winner based on id instead on pin
  index.js
  package-lock.json
  package.json
  server.js
  src/API/Dashboard/dashboard.js
  src/API/users/daily-winner.js
  src/API/users/register.js
  src/API/validators/register-validator.js
  src/Routes/routes.js
  test/test-daily-ladder.js
  test/test-register.js
  test/test-weekly-ladder.js
  test/util/mock-data.js
Labels: Logic update, Refactor

#26 Add local and test endpoint to cors whitelist
  server.js
Labels: deployment

#23 Create api endpoint for pto
  src/API/users/PTO.js
  src/API/validators/pto-validator.js
  src/Routes/routes.js
  test/test-pto.js
  test/test-server-status.js
Labels: enhancement

#25 Feature/update db api/users/antonio
  src/API/users/PTO.js
  src/API/users/checkin.js
  src/API/users/register.js
  src/API/users/weekly-ranking.js
  src/API/validators/checkin-validator.js
  src/Routes/routes.js
  test/test-checkin.js
  test/test-get-weekly-data.js
  test/test-register.js
Labels: Logic update, Refactor

#28 Enable cors for all
  server.js
Labels: bug

#31 Get arrival hour from user information to calculate the minutes of pe…
  src/API/users/checkin.js
  src/data/schema/user-schema.js
Labels: Logic update, enhancement

#32 Add arrival (hour) as an user object attribute and register the new s…
  src/API/users/register.js
  src/API/validators/register-validator.js
  test/test-register.js
Labels: Logic update, Refactor

#35 add experimental modules support for ES6
  package.json
Labels: Refactor

#36 little change on package json
  package.json
Labels: Refactor, help wanted

#37 remove type from package json to test the deployment
  package.json
Labels: bug, help wanted
